In [1]:
import  numpy  as np

In [2]:
#Basic array declaration

a= np.array([(1,2,3),(2,4,6)])
print(a)

[[1 2 3]
 [2 4 6]]


In [3]:
#number of elements in the aray
a.size

6

In [4]:
#number of rows and columns in the array
a.shape

(2, 3)

In [5]:
#initializing an array to ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#initializing an array to zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
#Listing numbers from a given range

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Listing numbers from a given range with an increamental value
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
#Generating a random number between 0 and 1
np.random.rand(2,2)

array([[0.96326947, 0.12116609],
       [0.20372627, 0.16389355]])

In [10]:
#Generating a random number between 2 and 7
np.random.randint(2,7,size=(2,2))

array([[2, 5],
       [3, 5]])

## 2. CONCATINATIONS

In [11]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#default concatination is a vertical one(0)
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#Horizontal concatination(1)
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

## 3.Reshaping

In [15]:
aa= np.array([(1,2,3),(2,4,6),(7,8,9),(10,11,12)])
aa

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
#NB,UNDERSTAND THE SIZE OF THE ARRAY AND YOU CAN ONLY RESHAPE USING THE MULTIPLES OF THAT SIZE .
aa.size

12

In [17]:
#MULTIPLES{(1,12),(2,6),(3,4)}

aa.reshape(1,12)

array([[ 1,  2,  3,  2,  4,  6,  7,  8,  9, 10, 11, 12]])

In [18]:
aa.reshape(2,6)

array([[ 1,  2,  3,  2,  4,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
aa.reshape(3,4)

array([[ 1,  2,  3,  2],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 4. Array self arrithmetic operations

In [20]:
#total sum of the array
aa.sum()

75

In [21]:
#summing rows
aa.sum(axis=1)

array([ 6, 12, 24, 33])

In [22]:
#summing columns
aa.sum(axis=0)

array([20, 25, 30])

## 5. Broadcasting

In [23]:
e=np.array([(1,2,3)])
f=np.array([(2,4,6)])
e+f

array([[3, 6, 9]])

In [24]:
e1=np.array([(1,2),(3,4),(5,6)])
e1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
f1=np.array([8,9])
f1

array([8, 9])

In [26]:
e1+f1

array([[ 9, 11],
       [11, 13],
       [13, 15]])

<H3><U>Broadcasting Rules</u>
    - size of each dimension should be same
    - or size of one of the dimensions should be 1
    
<h3><U>Solution figuring Rules</u>

-if the two arrays differ in their number of dimensions , the shape of the one with fewer dimension is padded with               ones on its leading side(left side).

-If the if the shape of the two arrays does not match in any dimension,the array with shape equal to 1 in thadimension  is stretched to match the other shape.

-if in any dimension the sizes disagree and neither equal to 1,an error is raised
     

In [27]:
e1.shape

(3, 2)

In [28]:
f1.shape

(2,)

In [29]:
e1+f1

array([[ 9, 11],
       [11, 13],
       [13, 15]])

In [30]:
x = np.array([10,20,30])
y = np.array([2,5,8,6])

In [31]:
#to be continued on broadcasting